language: java
notifications:
  email: false
script: mvn package
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: teapot-backend-reborn
env:
  global:
  - secure: Bdde1ENhVFIqCN6RgV1lXQsc46Q2khGsjiQxSUmeRptW1RwiP1hrG870zblkQf7p5i/++uomMq6BxQzEDR8TuBR5fJylk1PLAmOf5KSwo/3p8daXdHzjGiJhablBnYsh2knN8HRN/72m/GOEMUKs3K+tQ2vQqim4/SxkgJbi2TwKdOiP5lIoaYrrLnZzy/f5H+3EPi3F341We1Zj3WOL+ONJCSSQffzChBWHid0LRb6Ymsizg9FpmZZlsx2noxRyrN2C3VDhrgwizdqx0jaMjq+NyXfvKKsoRPXJoewT9zxWYiETHKUP8Ab5REBEsAP4lNsnQ3+BaGbwRXDQou8QaIFrokTbFOfoNNh89zSiqfsr0gol/diePoE3yTyBWh3ecmLzs7HiRajzmioVPE2dxqvWKmvEPVzJPhjpKUTaaJZDCl5vrd9Fz+4uZT2kRUrCwPQOd13S2HerxQAL9kUlGriiHxYRwAe1ecCzFzf8Cq6rAGc56VIpROuiaksOm8g+UwCxH49kHoPh2aLXAAeYyYLF2HY3EDotV2n6rKeKfrTFMLGJv9EPTZwKYlHWNOgi2uSCuTOVc+Yj7GeolLh7fUMA3S8ms0BLC/ThMufh8JGNJAYqL51xawsmqQPQ5jjWckmPiJIYE/rZaQ2wHLkozEogW2wx6udTWI1QJHxkbW8=
